config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  resources :users
  resources :posts, only: [:new, :create, :index]
  get '/login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'
  delete '/signout' , to: 'sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: { minimum: 6 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  validates :password, presence: true

  def remember
    encrypted_token = Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64)
    update_attribute(:remember_token, encrypted_token)
  end

  def forget
    update_attribute(:remember_token, nil)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper

  def log_in(user)
    session[:user_id] = user.id
    user.remember
    cookies.permanent[:remember_token] = user.remember_token
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :signed_in?, only: %i[new create]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    return unless (user = current_user)

    post = user.posts.build(post_params)
    if post.save
      flash[:success] = 'post saved successfully.'
      redirect_to root_url
    else
      flash[:danger] = 'Pleas enter valid post details'
      redirect_to new_post_path
    end
  end

  private

  def signed_in?
    flash[:danger] = 'Please log in first.' unless logged_in?
    redirect_to login_path unless logged_in?
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user&.authenticate(params[:session][:password])
      log_in(@user)
      redirect_to root_url
    else
      flash.now[:danger] = 'Please try again'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcom #{@user.name}, now you can see posts authors and create your own!"
      redirect_to root_url
    else
      flash.now[:danger] = 'please enter valid information.'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def logged_in?
    !current_user.nil?
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (remember_token = cookies[:remember_token])
      user = User.find_by(remember_token: remember_token)
      log_in(user) if user
      @current_user = user
    end
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_header.html.erb
<%= link_to "Home", root_url %>
<% if logged_in?%>
    <%= link_to("logout", signout_path , method: :delete) %>
    <%= link_to "Create New Post", new_post_path  %>
<% else %>
    <%= link_to "log in", login_path %>
    <%= link_to "Signup", signup_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'shared/errors'%>
    <%= yield %>
    
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1> posts </h1>
<ul>
    <% @posts.each do |post| %>
        <li>
            <h3><%= post.title %></h3>
            <p> <%= post.content %> </p>
            <% user = User.find(post.user_id)%>
            <% if logged_in? %>
                <p> author: <%= user.name %> </p>
            <% end %>
        </li><br/>
    <% end %>
<ul>

app/views/posts/new.html.erb
<h1>Create new post</h1>
<%= form_for @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit "Submit" %>
<% end %>

app/views/shared/_errors.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<% if @user && @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Signup" %>
<% end %>